/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package dynamicdep

import org.gradle.testfixtures.ProjectBuilder
import org.gradle.api.Project
import spock.lang.Specification

/**
 * A simple unit test for the 'dynamicdep.greeting' plugin.
 */
public class DynamicdepPluginTest extends Specification {
//    def "plugin registers task"() {
//        given:
//        def project = ProjectBuilder.builder().build()
//
//        when:
//        project.plugins.apply("dynamicdep.greeting")
//
//        then:
//        project.tasks.findByName("greeting") != null
//    }
}
